### ISSUE TITLE
Crash when sending string data

### ISSUE THREAD

**Issue by HenryNe** [HardingPoint/node-red-contrib-ftp-sftp#11]
https://github.com/gaskaj/node-red-contrib-ftp-sftp/blob/e79be185dfe070e06bce9fd83a38f424e8546855/ftp.js#L139

While sending string data as payload, node red crashed.
```
[http://www.hardingpoint.com] FTP Put:upload/1592590259044undefined
19 Jun 10:10:59 - [red] Uncaught Exception:
19 Jun 10:10:59 - TypeError: Cannot create property 'filename' on string '02032102FD0B0111'
    at Socket.<anonymous> (/usr/local/node-red/node_modules/node-red-contrib-ftp-sftp/ftp.js:139:50)
    at Socket.f (/usr/local/node-red/node_modules/node-red-contrib-ftp-sftp/node_modules/once/once.js:25:25)
    at emitOne (events.js:121:20)
    at Socket.emit (events.js:211:7)
    at TCP._handle.close [as _onclose] (net.js:557:12)
```

**Comment by HenryNe** [comment]
Fixed
